--外部キー制約を追加
CREATE TABLE TABLE3
(
    ID         NUMBER(10,0) DEFAULT 0 NOT NULL
   ,TABLE2_ID  NUMBER(10)
   ,COLUMN1    NUMBER(50)
   ,CONSTRAINT TABLE3_PK PRIMARY KEY (ID) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        --TABLESPACE KAKIP2
        STORAGE(INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
  ,CONSTRAINT "FK_TABLE3_TABLE2_ID" FOREIGN KEY ("TABLE2_ID")
	  REFERENCES "KAKIP2"."MADO_ORDER_MAIN" ("MADO_ORDER_MAIN_CODE") ENABLE 
)
PCTFREE 5
MAXTRANS 255
--TABLESPACE KAKIP2
STORAGE(INITIAL 6M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING;
COMMENT ON TABLE TABLE3 IS 'TABLE3';
COMMENT ON COLUMN TABLE3.COLUMN1     IS 'COLUMN1';
COMMENT ON COLUMN TABLE3.COLUMN2     IS 'COLUMN2';
