--実行は「スクリプトの実行」にて。
CREATE TABLE TABLE4
(
    ID             NUMBER(10,0) DEFAULT 0 NOT NULL
   ,COLUMN1       VARCHAR2(50)
   ,COLUMN_BLOB   BLOB
   ,COLUMN_CLOB   CLOB
   ,COLUMN_NCLOB  NCLOB
   ,COLUMN_RAW    RAW(2000)
   ,CONSTRAINT TABLE4_PK PRIMARY KEY (ID) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        --TABLESPACE KAKIP2
        STORAGE(INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
)
PCTFREE 5
MAXTRANS 255
--TABLESPACE KAKIP2
STORAGE(INITIAL 6M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING;
COMMENT ON TABLE TABLE4 IS 'TABLE4';
COMMENT ON COLUMN TABLE4.COLUMN1      IS 'COLUMN1';
COMMENT ON COLUMN TABLE4.COLUMN_BLOB  IS 'バイナリデータを格納';
COMMENT ON COLUMN TABLE4.COLUMN_CLOB  IS ' 文字データを格納';
COMMENT ON COLUMN TABLE4.COLUMN_NCLOB IS '各国語キャラクタ・セットの文字データを格納';
COMMENT ON COLUMN TABLE4.COLUMN_RAW   IS 'Oracle Databaseが解釈しないデータに使用。バイナリ・データやバイト文字列。グラフィックス、サウンド、文書またはバイナリ・データの配列';
