CREATE USER KAKIP2
IDENTIFIED BY KAKIP2
DEFAULT TABLESPACE KAKIP2
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;
GRANT CONNECT TO KAKIP2;
GRANT RESOURCE TO KAKIP2;
GRANT CREATE ANY VIEW TO KAKIP2;
GRANT CREATE LIBRARY TO KAKIP2;
GRANT CREATE DATABASE LINK TO KAKIP2;
GRANT CREATE SYNONYM TO KAKIP2;
GRANT DEBUG CONNECT SESSION TO KAKIP2;
GRANT DELETE ANY TABLE TO KAKIP2;
GRANT INSERT ANY TABLE TO KAKIP2;
GRANT SELECT ANY DICTIONARY TO KAKIP2;
GRANT SELECT ANY SEQUENCE TO KAKIP2;
GRANT SELECT ANY TABLE TO KAKIP2;
GRANT UNLIMITED TABLESPACE TO KAKIP2;
GRANT UPDATE ANY TABLE TO KAKIP2;
