create or replace FUNCTION MY_FUNCTION_02
RETURN NUMBER IS
  i number := -1;

  IN_PARAM1_LIST  MY_PACKAGE_01.NUM_TYPE_LIST;
  IN_PARAM2_LIST  MY_PACKAGE_01.CHAR_TYPE_LIST;
BEGIN

i := i + 1;
IN_PARAM1_LIST(i) := 0;
IN_PARAM2_LIST(i) := '00';

i := i + 1;
IN_PARAM1_LIST(i) := 1;
IN_PARAM2_LIST(i) := '11';

i := i + 1;
IN_PARAM1_LIST(i) := 2;
IN_PARAM2_LIST(i) := '22';

  MY_PACKAGE_01.MY_PROCEDURE_07(
    IN_PARAM1_LIST => IN_PARAM1_LIST,
    IN_PARAM2_LIST => IN_PARAM2_LIST
  );

  RETURN  SQLCODE;

EXCEPTION
    WHEN OTHERS THEN
    --DBMS_OUTPUT.PUT_LINE('エラーコード:'||SQLCODE);
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN SQLCODE;
END;
