create or replace FUNCTION MY_FUNCTION_02
RETURN NUMBER IS
  IN_PARAM1_LIST  MY_PACKAGE_01.NUM_TYPE_LIST;
  IN_PARAM2_LIST  MY_PACKAGE_01.CHAR_TYPE_LIST;
BEGIN

  IN_PARAM1_LIST(0) := 0;
  IN_PARAM1_LIST(1) := 11;

  MY_PACKAGE_01.MY_PROCEDURE_07(
    IN_PARAM1_LIST => IN_PARAM1_LIST,
    IN_PARAM2_LIST => IN_PARAM2_LIST
  );

  RETURN  SQLCODE;

EXCEPTION
    WHEN OTHERS THEN
    --DBMS_OUTPUT.PUT_LINE('エラーコード:'||SQLCODE);
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    RETURN SQLCODE;
END;
